# Generated by Django 3.2.1 on 2021-05-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_image',
            field=models.ImageField(blank=True, default='books/default.png', null=True, upload_to='books/'),
        ),
    ]
